### ISSUE TITLE
Missing scrollbar at init

### ISSUE THREAD

**Issue by ptz0n** [joehewitt/scrollability#1]
If you use UITableView as referance I'm missing the initial visibility of the scrollbar for orientation and context purpose. The user want to know how long (how many cells) and where in the TableView the user is located.

**Comment by jakemarsh** [comment]
This might be cleanly solved by implementing a version of `UITableView`'s `flashScrollIndicators` method.

Something like:

``` javascript
function flashScrollIndicator() {
    if(scrollbar) {
        scrollbar.style.opacity = '0.8';
        scrollbar.style.webkitTransition = 'opacity 0.2s linear';

        setTimeout(function() {
            scrollbar.style.opacity = '0';
            scrollbar.style.webkitTransition = 'opacity 0.2s linear';
        }, 450);
    }
}
```

**Comment by ptz0n** [comment]
Right on point.

**Comment by joehewitt** [comment]
Fixed.
