### ISSUE TITLE
How the scroll wrapper should function!

### ISSUE THREAD

**Issue by lifeiscontent** [joehewitt/scrollability#21]
I believe the wrapper should adhere to standards.

If you set your navigation-bar/tab-bar to fixed they become absolute positioned elements in Mobile Devices.

then if you set your content area to overflow-y: auto; you now have a vertical scroller inside of a desktop browser..

I think scrollablity should take advantage of this knowledge unless you decide to develop addition features that aren't currently supported in Desktop browsers.

**Comment by joehewitt** [comment]
That would be cool, but prohibitively expensive to find and maintain the list of all elements that have the overflow-y CSS property set on them.
