### ISSUE TITLE
require.js required?

### ISSUE THREAD

**Issue by Yuripetusko** [joehewitt/scrollability#27]
It sais that no dependencies inbvolved, but it looks like you are using require.js as export and requre methods are called.

**Comment by joehewitt** [comment]
There is a build step that strips out the require calls.

**Comment by Yuripetusko** [comment]
oops :) Thanks

**Comment by max-mapper** [comment]
@joehewitt can you put build step instructions in the readme?

**Comment by speedmax** [comment]
@joehewitt +1 for build instruction

**Comment by joehewitt** [comment]
There are no build instructions because I don't really want anyone using Scrollability. I'm not maintaining it. Sorry for not putting that in the README.

**Comment by max-mapper** [comment]
@joehewitt some of the methods used in scrollability are useful on their own (precompiling keyframes etc), but to truly learn from them it helps to be able to recompile the library as-is with logging features inserted
