### ISSUE TITLE
Is scrollability still relevant after -webkit-overflow-scrolling: touch

### ISSUE THREAD

**Issue by mech** [joehewitt/scrollability#30]
I have read some said that scrolling is improved in iOS 5 with -webkit-overflow-scrolling: touch

I am wondering if my target platform is iOS 5 will I need to use scrollability or there is some feature on scrollability that is very much still relevant?

**Comment by yourfavorite** [comment]
It depends on the use. Things such as snapping to positions isn't possible without javascript of some kind. Also in my experience the iOS implementation of inertial scrolling isn't perfect yet. I'm currently working on a project that will only work on iOS5 and I'm still using a modified version scrollability.

**Comment by jamieholst** [comment]
In my experience -webkit-overflow-scrolling: touch works pretty well as long as you keep an eye on parent nodes and position: fixed

That said, there's still no way to have JavaScript events fired during scrolling, so Scrollability and the likes are still required if you e.g. want to lazy-load content during scroll.
